#!/bin/sh

# see Chapter 8 of Debian Linux Kernel Handbook

set -e

# /etc/kernel/{postinst.d,postrm.d}/zz-flash-kernel conffile still present, but
# flash-kernel removed
if ! which flash-kernel >/dev/null 2>&1; then
    exit 0
fi

# this script is used as postinst.d and postrm.d script; this is used to
# differentiate between the two
self="$0"

# see 8.1, Kernel hooks
abi="$1"
# ignored
_vmlinuz="${2:-/boot/vmlinuz-$abi}"
set -- $DEB_MAINT_PARAMS
action="$1"
action="${action#\'}"
action="${action%\'}"
# ignored
_version="$2"
_version="${version#\'}"
_version="${version%\'}"

# only call flash-kernel once on install, upgrade, removal or purge
case "$(basename "$(dirname "$self")")/$action" in
  postinst.d/configure|postrm.d/remove)
    exec flash-kernel "$abi"
  ;;
esac

